services:
  bot:
    container_name: bot
    build: .
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    restart: unless-stopped